Feature/58 login logout
P7-Team/P7-WebService pull request #61
Opened 2021-11-17 13:09 UTC by naitoarekkus

Clients can now create themselves (persistence is not implemented)
They can login and get a token.
They can logout and invalidate their token

2021-11-17 13:31 UTC, MikaelVM commented on WebService/Models/Token.cs
> +            Tkn = token;
Lille ting, "Tkn" opfuskere hvad variablen er til andre steder den bliver nævnt, så rammer readability en lille bitte del.

2021-11-17 13:56 UTC, Kaliahh requested changes
Småting

2021-11-17 13:56 UTC, Kaliahh commented on WebService-UnitTests/ContentReaderTest.cs
> +            // Steup
```suggestion
            // Setup
```

2021-11-17 13:56 UTC, Kaliahh commented on WebService-UnitTests/ContentReaderTest.cs
> +            ReadStreamContent_WithUnicodeEncoding_StreamWithContentUsingSameEncoding_ReturnsIncorrectString()
```suggestion
            ReadStreamContent_WithUnicodeEncoding_StreamWithContentUsingSameEncoding_ReturnsCorrectString()
```

2021-11-17 13:56 UTC, Kaliahh commented on WebService/Models/Token.cs
> +            Tkn = token;
++

2021-11-17 14:00 UTC, MikaelVM submitted a review, later dismissed

2021-11-18 07:35 UTC, Kaliahh approved these changes

2021-11-18 07:35 UTC, MikaelVM approved these changes
Seems good.

2021-11-18 07:35 UTC, merged