Feature/39 request finished batch
P7-Team/P7-WebService pull request #62
Opened 2021-11-22 12:18 UTC by AxialDark

close #39

2021-11-22 12:21 UTC, MikaelVM commented on WebService/Models/BatchStatus.cs
> +            Done = done;
Hvorfor er Done en int og ikke en bool?

2021-11-22 12:26 UTC, MikaelVM submitted a review, later dismissed

2021-11-22 12:41 UTC, AxialDark commented on WebService/Models/BatchStatus.cs
> +            Done = done;
I have made change

2021-11-23 07:20 UTC, soenderby commented on WebService/Services/TokenStore.cs
> +    public class TokenStore : ITokenStore
Jeg kan ikke se noget tests for denne klasse. Hvad ligger til grund for dette

2021-11-23 07:30 UTC, soenderby requested changes
Der er ikke tilføjet nogle tests, jeg har antaget at dette er grundet at det ikke er nødvendigt og at det er OK. Jeg har dog efterladt en kommentar hvor jeg mener at der mangler tests.

2021-11-23 08:31 UTC, soenderby approved these changes

2021-11-23 08:39 UTC, MikaelVM approved these changes

2021-11-23 08:40 UTC, merged