Revised batch receive
P7-Team/P7-WebService pull request #68
Opened 2021-12-01 14:18 UTC by AxialDark

2021-12-01 14:29 UTC, dkalaxdk requested changes

2021-12-01 14:29 UTC, dkalaxdk commented on WebService/Controllers/BatchController.cs
> +            return Ok(statusList);
```suggestion
            return Ok(System.Text.Json.JsonSerializer.Serialize(statusList));
```

2021-12-01 14:29 UTC, dkalaxdk commented on WebService/Services/Repositories/BatchFileRepository.cs
> +
Endte den med at skulle bruges?

2021-12-01 14:30 UTC, AxialDark commented on WebService/Services/Repositories/BatchFileRepository.cs
> +
Tror jeg ikke, men hvorfor risikere det?

2021-12-01 14:30 UTC, dkalaxdk approved these changes

2021-12-02 07:45 UTC, soenderby approved these changes
🐙

2021-12-02 07:47 UTC, soenderby approved these changes

2021-12-02 07:47 UTC, dkalaxdk approved these changes

2021-12-02 07:48 UTC, merged