Integrate scheduler with db
P7-Team/P7-WebService pull request #70
Opened 2021-12-02 08:46 UTC by soenderby

2021-12-02 08:49 UTC, dkalaxdk submitted a review, later dismissed

2021-12-02 09:11 UTC, AxialDark requested changes
Næsten approved der er bare 2 steder hvor vores standard ikke bliver fulgt

2021-12-02 09:11 UTC, AxialDark commented on WebService/Controllers/TaskController.cs
> +            User user = providerDto.ToUser();
Bare for det matcher en tidligere suggestion
```suggestion
            User user = providerDto.MapToUser();

```

2021-12-02 09:11 UTC, AxialDark commented on WebService/Services/EligibleBatchesService.cs
> +                                            WHERE U.points >= @Points", new { Points = pointLimit });
Når jeg læser det her så tænker jeg egentlig at jeg ville have foretrukket at alt vores SQL blev skrevet i samme stil.
Det er mere gennemskueligt, synes jeg personligt 👍

2021-12-02 09:15 UTC, AxialDark approved these changes
Approve

2021-12-02 09:15 UTC, dkalaxdk approved these changes

2021-12-03 07:32 UTC, merged

2021-12-03 07:59 UTC, MikaelVM approved these changes
Seems good, well done 👍